# .sqa/config.yml - jenkins-pipeline-library configuration file
sqa_criteria:
  qc_style:
    repos:
      {{ cookiecutter.package_slug }}:
        container: testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.sty
  qc_coverage:
    repos:
      {{ cookiecutter.package_slug }}:
        container: testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.cov
  qc_security:
    repos:
      {{ cookiecutter.package_slug }}:
        container: testing
        tox:
          tox_file: tox.ini
          testenv:
            - qc.sec

environment:
  GIT_COMMITTER_NAME: "{{ cookiecutter.author_name }}"
  GIT_COMMITTER_EMAIL: "{{ cookiecutter.author_email }}"
  LANG: C.UTF-8

timeout: 600
